### ISSUE TITLE
Distinguishing globals from non-globals with the same name

### ISSUE THREAD

**Issue by fergald** [jackbsteinberg/get-originals-rewriter#12]
We should either be able to distingiush them or be able to enforce in e.g. eslint that we cannot shadow globals with locals of the same name.

**Comment by domenic** [comment]
This should mostly be implemented. What remains is to add tests that contain cases like this (where something shadows the global) and ensure that it doesn't get rewritten. Such tests cases need to cover all possible combinations of { namespace function, static method, method, getter, setter, constructor } x { JS, web }.

I'll rename the issue to focus on tests.

**Comment by fergald** [comment]
Maybe I'm missing something but `isConsoleCallExpression` just looks at the name and so `clean-console.js` looks to me like it would fail such a test right now.

**Comment by domenic** [comment]
Yeah, I think the console transform probably wouldn't pass such a test, that's true. The others would.

**Comment by jackbsteinberg** [comment]
I think this is resolved, including the console issue, via #60 and #67 so I'm going to close this for now
