### ISSUE TITLE
Converting global functions and importing from originals

### ISSUE THREAD

**Issue by jackbsteinberg** [jackbsteinberg/get-originals-rewriter#44]
Functions on the window object can be written without a property access expression like this:

```
prompt('Pick a number');
alert('Hello World!');
```

However, global functions can be written in the same way:

```
eval('2+2');
parseFloat('5.45');
```

At this point the code in #36 would change the above to:

```
Window_eval('2+2');
Window_parseFloat('5.45');
```

Which is probably not where the original should be coming from. What's the correct way to handle this case?

**Comment by domenic** [comment]
I'm not sure I understand what distinction you're making. The window is the global object, and the rewrite seems correct to me.
