### ISSUE TITLE
Test that Babel is *not* applied by default

### ISSUE THREAD

**Issue by domenic** [jackbsteinberg/get-originals-rewriter#6]
#5 indicates that by default our code will get babel-transformed. We should add some tests, e.g. with private fields, to test that this does not happen. If it does happen, we should figure out how to turn it off.

**Comment by jackbsteinberg** [comment]
Oh I think I figured out what's going on - it says the **transform** file (not the test files) will be babel transformed according to the jscodemod options:

```
--(no-)babel              apply babeljs to the transform file
                                (default: true)
```

What should I be added to test that this doesn't happen? Putting something like private fields in the tests won't add anything and further still it won't run.

**Comment by domenic** [comment]
Oh, I see, that's interesting. I guess it doesn't really matter, so we can just leave as-is? Or maybe modify the npm script to pass `--no-babel`?

**Comment by domenic** [comment]
Let's use this issue to track adding `--no-babel` to the npm script, to give a minor speedup, and then open a second issue to track making sure that our parser can handle modern language features. The OP of this issue currently conflates those two.

**Comment by jackbsteinberg** [comment]
Issue #8 added to track that our parser can handle modern language features

**Comment by domenic** [comment]
Closing this in favor of #30.
