### ISSUE TITLE
Change test file extensions to .mjs

### ISSUE THREAD

**Issue by domenic** [jackbsteinberg/get-originals-rewriter#7]

**Comment by jackbsteinberg** [comment]
Looks like jscodemod automatically adds the `.input.js` and `.output.js` to the test files in their [`runTest` helper](https://github.com/facebook/jscodeshift/blob/master/src/testUtils.js#L59).

What I could do is copy over their [testUtils.js](https://github.com/facebook/jscodeshift/blob/master/src/testUtils.js) file and modify it to support both `.js` and `.mjs`

**Comment by domenic** [comment]
That's annoying. I'm surprised there is no way to configure defaults for the test runner like there is for the command-line argument.

Let's not copy the code for now; instead let's open an issue on jscodeshift, asking them if they'd accept a pull request to configure it, and wait to see what they say.

**Comment by jackbsteinberg** [comment]
Opened: https://github.com/facebook/jscodeshift/issues/336 to address this

**Comment by domenic** [comment]
This can be solved as part of #30.
